### ISSUE TITLE
[onert] always run in tracing mode

### ISSUE THREAD

**Issue by glistening** [Samsung/ONE#10617]
During #10610, I've found our `LinearExecutor` always run in tracing mode.

Without profiling enabled, it should run `else` code, which has no overhead due to profiling.

https://github.com/Samsung/ONE/blob/e289e63b764e3296e3726726b45a687eaf442ac8/runtime/onert/core/src/exec/LinearExecutor.cc#L56-L72

But, current code always run in tracing mode.

https://github.com/Samsung/ONE/blob/e289e63b764e3296e3726726b45a687eaf442ac8/runtime/onert/core/src/exec/LinearExecutor.cc#L29-L41

Maybe, `tracing_ctx` is always created while it was created conditionally.

We need to fix it.

**Comment by glistening** [comment]
```diff
$ git -p diff
diff --git a/runtime/onert/core/src/exec/LinearExecutor.cc b/runtime/onert/core/src/exec/LinearExecutor.cc
index a64dadcb1..d75639f56 100644
--- a/runtime/onert/core/src/exec/LinearExecutor.cc
+++ b/runtime/onert/core/src/exec/LinearExecutor.cc
@@ -29,6 +29,7 @@ void LinearExecutor::executeImpl()
   if (_tracing_ctx)
   {
     auto profiling_subg_index = _tracing_ctx->getSubgraphIndex(&_graph);
+    printf("[G] LinearExecutor runs in tracing mode\n");

     _subject.notifySubgraphBegin(profiling_subg_index);
     for (auto &&code : _code)
```
```
$ Product/out/unittest/nnfw_api_gtest
[==========] Running 562 tests from 34 test suites.
[----------] Global test environment set-up.
[----------] 225 tests from GenModelTest
[ RUN      ] GenModelTest.UnusedConstOutputOnly
[G] LinearExecutor runs in tracing mode
[       OK ] GenModelTest.UnusedConstOutputOnly (5 ms)
[ RUN      ] GenModelTest.UnusedConstOutputAndAdd
[G] LinearExecutor runs in tracing mode
[G] LinearExecutor runs in tracing mode
[       OK ] GenModelTest.UnusedConstOutputAndAdd (1 ms)
[ RUN      ] GenModelTest.UsedConstOutput
[G] LinearExecutor runs in tracing mode
[       OK ] GenModelTest.UsedConstOutput (1 ms)
[ RUN      ] GenModelTest.TensorBothInputOutput
[G] LinearExecutor runs in tracing mode
[G] LinearExecutor runs in tracing mode
...
```
```

**Comment by hseok-oh** [comment]
FYI) Below is history.

At first, Executor was designed to call notifier always.
If tracer is not enabled, there is no observer. 

https://github.com/Samsung/ONE/blob/1f722a2129ff9e45366adc6a62b7324b8c83ce2a/runtime/onert/core/src/exec/LinearExecutor.cc#L24-L36

`tracing context` was introduced later to support profiling on control flow model. (#4901)

Skipping to call notifier was workaround to support pipeline because pipeline compiler did not generate `tracing context`. (#6973)

**Comment by glistening** [comment]
@hseok-oh Thank you for history. I thought I have to remove the overhead by notification system because:

1. I didn't know the history.
2. I would like to remove the overhead of `notify...` though it may not have observer. It does more. 

Then, as I understand,

We may remove `else` blocks since there is no pipeline any longer. `if (_tracing_ctx)` check can also be removed.

**Comment by hseok-oh** [comment]
>We may remove `else` blocks since there is no pipeline any longer.

Unfortunately, multi model compiler doesn't generate tracing context.

Based on history, I think we always called `notifyXXX` because its overhead is thought as neglectable . But I also think your suggestion is reasonable. And I think `tracing context` checking may depend on decision to generate `tracing context` always or not. 

We can skip `tracing context` generation if we don't need this on common case. And we can add skipping notifier call if `tracing context` is null (and additionally there is no observer in `_subject`).

**Comment by glistening** [comment]
Thank you for explanation. I close this PR since I confirmed it is intended. Let's make issue if optimization becomes necessary.
