### ISSUE TITLE
Compiler Debian package 1.24.0 nightly is not published

### ISSUE THREAD

**Issue by seanshpark** [Samsung/ONE#10853]
Compiler Debian package 1.24.0 nightly is not published.

**Comment by mhs4670go** [comment]
https://github.com/Samsung/ONE/blob/d15462c67b973001dd69670cf5b028cb8f8c49d7/infra/scripts/docker_build_nncc.sh#L69-L70

This is because of mismatch between the version of compiler and the one of runtime. CI build script for compiler is looking at the version of the runtime. Let's use the version from `vconone`.

**Comment by hseok-oh** [comment]
@Samsung/one_onert  We need to update runtime nightly version to 1.24.0.

**Comment by mhs4670go** [comment]
> @Samsung/one_onert We need to update runtime nightly version to 1.24.0.

I posted related PR. Maybe you can reply this comment https://github.com/Samsung/ONE/pull/10813#issuecomment-1556333847.

**Comment by seanshpark** [comment]
@hseok-oh , change has landed. can you please trigger Debian package build?

**Comment by hseok-oh** [comment]
New packages are uploaded.

**Comment by seanshpark** [comment]
done
