### ISSUE TITLE
[tflchef] Support multiple subgraphs

### ISSUE THREAD

**Issue by BalyshevArtem** [Samsung/ONE#12506]
### What

Let's support multiple subgraphs in `tflchef-reverse`

### Why

To generate recipes for tflite models with multiple subgraphs (for example for https://github.com/Samsung/ONE/pull/12319#issuecomment-1893463618)

**Comment by seanshpark** [comment]
from https://github.com/Samsung/ONE/pull/12516#discussion_r1464090301

### about the changes
1/ all the `build()` for ops have to be changed
-> current `tflchef::ModelRecipe *model_recipe` argument cannot add op for sub-graphs
-> protobuf was designed like this. there was only one sub-graph when reverse was introduced and then extended with adding `Graph` for multiple sub-graphs, thus `add_operation()` exist in `tflchef::ModelRecipe` and also `tflchef::Graph`.
-> this is technical-debt 

2/ `TFliteImport *import` is not used for all `build()`
-> this turned out like `build()` method design was not good

### requirements to support multiple sub-graph in recipe generation
1/ support adding new Op in `tflchef::Graph`
2/ do not change files in `Op` folder
-> this seems impossible as we have to call `tflchef::Graph::add_operation()` somehow
3/ reduce changes
4/ ...


### what I can think of ...

as-is
```cxx
tflchef::Operation *
build(const tflite::Operator *op, TFliteImport *import, tflchef::ModelRecipe *model_recipe) const
```
is called from
```cxx
    if (const auto *graph_builder = TFliteOpRegistry::get().lookup(builtincode))
    {
      auto operation = graph_builder->build(op, &tflite_import, model_recipe.get());
```

prop 1: replace with new context class 
```cxx
tflchef::Operation *
build(const tflite::Operator *op, ChefContext *cctx) const
{
  auto operation = cctcx->add_operation();
```

prop 2: create `tflchef::Operation` object from caller and pass
```cxx
void
build(const tflite::Operator *op, tflchef::Operation *op) const
```
call from
```cxx
    if (const auto *graph_builder = TFliteOpRegistry::get().lookup(builtincode))
    {
      tflchef::Operation *operation = graph ? graph->add_operation() : model_recipe.add_operation();
      graph_builder->build(op, operation);
```

prop 3: ... will update if any other comes up

**Comment by mhs4670go** [comment]
There are two things that I came up with.

1. Revise existing proto file and all the recipe files accordingly.

```proto
message Graph {
  repeated Operand operand = 1;
  repeated Operation operation = 2;
  repeated string input = 3;
  repeated string output = 4;
  optional string name = 5;
}

message ModelRecipe {
  optional uint32 version = 1 [default = 1];
  repeated Graph graph = 2;
  repeated SignatureDef signature_def = 3;
}
```

2. Use c++ template feature

Since `Modelrecipe` api covers all the `Graph` api, template feature reduces otherwise required if condition.

**Comment by seanshpark** [comment]
> Revise existing proto file and all the recipe files accordingly.

This will require all existing recipe files to follow the schema...

**Comment by seanshpark** [comment]
> I prefer this second variant, anyway, I can do any of them. Which one should I choose?

first idea using `ChefContext` is that we won't have to change the `build()` prototype anymore
but to change `ChefContext` members when needed.

mixing them would be like

prop 3;
```cxx
struct RecipeChefContext {
  tflite::Operator *tflop = nullptr;
  tflchef::Operation *chefop = nullptr;
  // add more if needed
};

void build(RecipeChefContext *ctx) const
```

**Comment by seanshpark** [comment]
Thanks for accepting my proposal and for laborious update!

**Comment by BalyshevArtem** [comment]
thank you @seanshpark!
All merged, close it.
