### ISSUE TITLE
[onert/train] what diff btw `nnfw_input_size() -> nnfw_train_prepare()` and `nnfw_train_prepare() -> nnfw_input_size()`?

### ISSUE THREAD

**Issue by YongseopKim** [Samsung/ONE#12510]
I've been drafting a new GenModelTest for train in tests/nnfw_api
- REF: https://github.com/Samsung/ONE/issues/12501

While working on it, I'm facing a problem that I don't understand AFAIK. 😥

If the model has an input, the following code's `ASSERT_EQ` passes.
```cpp
    // Input buffer settings
    uint32_t num_inputs;
    nnfw_input_size(_so.session, &num_inputs);
    ASSERT_EQ(num_inputs, 1); // **PASS**
    nnfw_train_prepare(_so.session);
```

However, if `nnfw_train_prepare()` is called before  `nnfw_input_size()`, it fails.
```cpp
    nnfw_train_prepare(_so.session);
    // Input buffer settings
    uint32_t num_inputs;
    nnfw_input_size(_so.session, &num_inputs);
    ASSERT_EQ(num_inputs, 1); // **FAILED**: num_inputs == 2
```

Is there any difference between calling `nnfw_input_size()` followed by `nnfw_train_prepare()` and calling `nnfw_train_prepare()` followed by nnfw_input_size()`?

I'm currently investigating the following code in `nnfw_api_internal.cc` but I still don't understand it.
```cpp
uint32_t nnfw_session::getInputSize()
{
  if (isStateInitialized())
    throw std::runtime_error{"Model is not loaded yet"};

  if (isStateModelLoaded())
    return _nnpkg->inputSize();

  // Session is prepared (general inference)
  return _compiler_artifact->_executors->inputSize();
}
```

If you know anything about this, please let me know. 😄

/cc @Samsung/one_onert

**Comment by YongseopKim** [comment]
I got it! Great answer! Thank you for @jyoungyun .

**Comment by YongseopKim** [comment]
```cpp
    nnfw_train_prepare(_so.session);
    // Input buffer settings
    uint32_t num_inputs;
    nnfw_input_size(_so.session, &num_inputs);
    ASSERT_EQ(num_inputs, 2); // num_inputs = input + expected_output
```

**Comment by hseok-oh** [comment]
@jyoungyun @YongseopKim 
IMO, we need to add comment on `nnfw_train_prepare` about this: when `nnfw_input_size()` and `nnfw_output_size()` is called after `nnfw_train_prepare`

**Comment by jyoungyun** [comment]
> IMO, we need to add comment on `nnfw_train_prepare` about this: when `nnfw_input_size()` and `nnfw_output_size()` is called after `nnfw_train_prepare`

Well, the `nnfw_input_size()` and `nnfw_output_size()` should be called before `nnfw_train_prepare`.
The `expected label` input will be added as the count of `nnfw_output_size()`. If the user gets the input size(called A) after `nnfw_train_prepare` api, the input size(A) contains both original input size and newly added expected label input size.
The user should distinguish between the actual input size and the expected input size from the input size(A) to put data into ONERT.

I will add a comment about this behavior to the `nnfw_train_prepare` API description. We couldn't modify the `nnfw_input_size` and `nnfw_output_size` api description because the location is `nnfw.h`.

**Comment by ragmani** [comment]
We also consider how to remove training-related information such as expected input and loss op from a trainable graph when exporting the graph to circle+ model.
