### ISSUE TITLE
[circle2circle] Check file size > 2G with unet

### ISSUE THREAD

**Issue by seanshpark** [Samsung/ONE#14074]
Logs of issues with our 4G unet internal model.

This model is converted from ONNX.
- part of #12732

tasks
- [x] resolve model conversion with internal `one-import-onnx-ext` tool
- [ ] ...

**Comment by seanshpark** [comment]
`Reshape` Op `shape` with value of `[0, 12, -1]`
- `0` can be treated as `1`

**Comment by seanshpark** [comment]
```
[luci] Shape for output #0 not same
[luci]    8014 [1,4,1,1] vs [1,4,128,128]
ERROR: Optimized graph is invalid
```

**Comment by pcs1265** [comment]
I wrote some code that supports dynamic shape inference for Conv2D operations quite a while ago. https://github.com/Samsung/ONE/pull/13950

It was related to Yamnet (https://github.com/Samsung/ONE/issues/13790), but I abandoned it because the height and width were static in Yamnet, so there were no issues related to Conv2D.

In conclusion, Conv2D operations do not support dynamic shapes currently.
All dimensions of the ifm shape must be known except for the batch size.
If input has unknown dimmension, the dim will be calculated as 0.

Since I can't access detailed info, I might be wrong about this is related to dynamic shapes.
Could you check if [this draft PR(#13950)](https://github.com/Samsung/ONE/pull/13950) will help address this issue?

**Comment by seanshpark** [comment]
@pcs1265 , thanks for the comment! no worry.
there are lots of issues with this internal model that may take some time and I'll be working on it.
if you like to contribute later after SAFFY program, please be tuned :)

**Comment by pcs1265** [comment]
We have always appreciated for your kind advice to us!
As you mentioned, it can take some time to resolve this issue.
I have created an issue regarding dynamic shape support for Conv2D/DepthwiseConv2D, which I expect will help with this problem and is also related to our Yamnet issue.

If you have time, could you advise on one of the three methods I described here? https://github.com/Samsung/ONE/issues/14115
Thank you!

**Comment by seanshpark** [comment]
done
