### ISSUE TITLE
[onert] macOS support

### ISSUE THREAD

**Issue by wateret** [Samsung/ONE#269]
As we are making this project Opensource it would be awesome to make `onert` buildable and runnable on macOS.

Is anybody interested in macOS support?

**Comment by wateret** [comment]
With #2228 now the core modules are built but still have some issues with `boost` libs. Some tools are dependent on it.

**Comment by glistening** [comment]
With #2228, on my mac, I have the following error:
```
CMake Error at /Users/gyu/one/tests/tools/nnpackage_run/CMakeLists.txt:35 (target_link_directories):
  Unknown CMake command "target_link_directories".
```
because I use cmake `1.12.1` and `target_link_directories` is introduced since `1.13`.
Furthermore, I succeed to build `onert` without  the lines `target_link_directories`.
Thus, I would like to remove those lines if others confirmed that building `onert` works without those lines on their mac.

**Comment by wateret** [comment]
#2685 resolved it. Closing
