### ISSUE TITLE
[nnfwapi] What if a NNPackage contains multiple models?

### ISSUE THREAD

**Issue by wateret** [Samsung/ONE#2736]
https://github.com/Samsung/ONE/blob/500ad6eea910cdf8a574634b6f6b4d5f0dfcc7d3/nnpackage/spec/10_packaging_and_manifest.md#4-manifest

Shows that there can be many models in a package.

So far NNFW API assumed that there is only one model file in NNPackage. API will need a big change if we want to support multiple models.

**Comment by glistening** [comment]
@wateret  

### Option 1. Create session for each model in same nnpackage

```c
NNFW_STATUS nnfw_load_model_from_file(nnfw_session *session, const char *package_file_path,
                                      uint32_t model_idx = 0);
```

@chunseok and I thought to have this form when we design nnfw api. But we didn't. Because:
- I would like to introduce API when the use case of multiple model becomes concrete.
- `model_index` could be added in `nnfw_load_model_from_file` later with default value `0` without breaking existing API.

If we have nnpackage in directory like now, it has very little additional overhead to load several time because it just read `MANIFEST` and read the model file at `model_idx`.

### Option 2. Use a only session for nnpackage

It will require more changes in nnfw API.

----

I assume the how the models will be used is the scope of application. If we would like to embed more information about the relationship between models, it would require more change, and I don't have much idea at this moment.

**Comment by wateret** [comment]
cc: @chunseoklee

**Comment by wateret** [comment]
@glistening Option 1 would be the best option for now. 😄

**Comment by lemmaa** [comment]
It is only a reference opinion, not intended to directly affect the current work. :)

My first imagination of nnpackage was considering a static partition of the graph for multiple backends. Currently, multiple models of the nnpackage spec do not appear to reflect my imagination, but I would like some thoughts on that.

When a partition is assumed, it is necessary to define connection information between sub-models. It will be able to add to the manifist.

A simpler way is to assume that the sub-models are partitioned in index order. In that case, the output of the previous model should be compatible with the input of the next model.

This idea will also help in the design for interworking with heterogeneous binary models such as DSP and NPU.
