### ISSUE TITLE
[onert] Quantization implementation reference

### ISSUE THREAD

**Issue by hasw7569** [Samsung/ONE#2806]
tensorflow seems to have two implementation of some operators
ex) tanh -> **tensorflow/lite/kernels/activation.cc** and **tensorflow/lite/micro/kernels/tanh.cc**

I guess major difference of two implementation is existence of lookup table.

first implementation creates and uses lookup table, so it takes more memory but fast than second one.

when we port some implementation of quantization, It makes us confuse.

which one do we refer ?

please give me your opinion.

**Comment by lemmaa** [comment]
@hasw7569 , as you probably already know, `tensorflow/lite/micro/kernels/*` is an implementation for low-end devices. The ARM Cortex-M family will be a suitable reference target. Since the performance of our default target device is higher than that, it would be appropriate to refer to `tensorflow/lite/kernels/*` for now.

**Comment by hseok-oh** [comment]
Outdated question.
