### ISSUE TITLE
Huge venv for nncc release

### ISSUE THREAD

**Issue by seanshpark** [Samsung/ONE#3095]
As our tf2tflite.py script uses TensorFlow lite converter, we need users to install TensorFlow or we need to include this in our release package: https://github.com/Samsung/ONE/releases

Downloading huge several hundred megabytes is not a good thing; and uploading to `releases` page also.

Current status
- `nncc-1.6.1.tar.gz` file in `releases` download page does not contain `venv` binaries
- there is no guide how to prepare this

Let's solve this issue.

**Comment by seanshpark** [comment]
As I'm working on `Compile frontend drivers` #3018 issue , I came up with providing a command like `one-prepare-venv` that will prepare the virtual environment. If it is already prepared then do nothing.

User just has to run once. Or if there is any kind of  setup process, it can invoke this command as the last step.

**Comment by seanshpark** [comment]
CC @lemmaa

**Comment by lemmaa** [comment]
@seanshpark , I actively agree to provide a basic venv install script.

In addition, I would like a brief manual setup guide document in case the installation script fails.

Just suggestion,

Also, since users may have their own venv settings, it would be nice to be able to set the required venv path for one CLI as an env variable.
For example

```
set ONE_VENV_TF1=${HOME}/my_venv/tensorflow-1.13.2
set ONE_VENV_TF2=${HOME}/my_venv/tensorflow-2.3.0-rc0
```

In one CLI script, `source ${ONE_VENV_TF2}/bin/activate` will activate venv for Tensorflow 2.x.

**Comment by seanshpark** [comment]
I think we can close this issue. There's a guide and script in our release binary.
