### ISSUE TITLE
[onert] What is UserTensor, ManagedTensor, ConstTensor, StaticTensor, ExternalTensor ...?

### ISSUE THREAD

**Issue by glistening** [Samsung/ONE#3240]
Related: https://github.com/Samsung/ONE/pull/3228#issuecomment-659216196

I am seeing terms `ExternalTensor`, `UserTensor`, managed tensor from recent PRs #3228, #3229, #3102, ....

I am not familiar with them. Maybe I am not the first people who don't know them — https://github.com/Samsung/ONE/pull/3102#issuecomment-658665259, https://github.com/Samsung/ONE/pull/3102#discussion_r455510607
Thus, It would be good if someone kindly explains them in one place so that other members could find out the information easily.

I gathered information from several comment here and there.

Term | The opposite Term | What is it?
-- | -- | --
? |  ExternalTensor | https://github.com/Samsung/ONE/pull/3102#discussion_r455573649, https://github.com/Samsung/ONE/pull/3228#issuecomment-659224119 — Still not clear
StaticTensor | _(perhaps)_ DynamicTensor | Whether the ~allocation is~ shape can be determined at prepare time or execution time. Note 1: allocation can be made right after shape is calculated. However, we can delay allocation to some moment. (we don't have such code yet but refer to https://github.com/Samsung/ONE/issues/2525#issuecomment-658501660 for possible implementation. Therefore `assert(buf)` is recommended before write data into allocated memory. <br>Note 2: A tensor must be one of `static tensor` or `dynamic tensor` and use `ITensor::is_dynamic()`.
ConstTensor | NonConstTensor | Is it const or not
ManagedTensor | ???Tensor |  Is it managed by `TensorManager`
UserTensor | ? | https://github.com/Samsung/ONE/pull/3102#issuecomment-658677553
PortableTensor | ? |  https://github.com/Samsung/ONE/pull/2492

Could you please anyone check and update/fix?

@wateret, @YongseopKim

**Comment by wateret** [comment]
https://github.com/Samsung/ONE/pull/3228#issuecomment-659795122

**Comment by YongseopKim** [comment]
@wateret explained about ManagedTensor and ExternalTensor to me. Let me summarize.
- A Backend has a TensorRegistry.
- A TensorRegistry is a place for registring and holding tensors.
- A TensorRegistry has tensors as two types(You can imagine two divided pools)
  - Type ManagedTensors: these tensors will be managed by the owned backend directly.
  - Type ExternalTensors: these tensors will be managed by the other backend. It is meaning that C backend allocates a tensor so that manage it, but D backend will use the tensor as an external tensor.
- Therefore, a tensor should be in a TensorRegistry as a managed tensor but the tensor could be in another TensorRegistries as an external tensor.

**Comment by wateret** [comment]
RENAMED

ManagedTensors → NativeTensors
ExternalTensors → MigrantTensors (To distinguish it with cpu backend's `ExternalTensor`)

**Comment by wateret** [comment]
@YongseopKim Could you please write doxygen comments for cpu backend's `ExternalTensor` as well?

**Comment by YongseopKim** [comment]
@wateret sure. I'll upload soon.

**Comment by glistening** [comment]
I think the term is almost described here and renamed (e.g. #4271)
