### ISSUE TITLE
[Onert] Add Log_softmax op to support quantization

### ISSUE THREAD

**Issue by hasw7569** [Samsung/ONE#3495]
parent issue #1715 

I will make PR for Log_softmax quantization.

**Comment by hseok-oh** [comment]
@hasw7569 Any progress?

**Comment by hasw7569** [comment]
almost done ..
I ported `optimized_ops::Log_softmax` kernel from tensorflow to my local enviroment.
but we don't have nnapi testcase for Log_softmax (about quantization).
so I was trying to refer tensorflow testcode `tensorflow/lite/kernels/Activations_test.c -> LogSoftmaxUint8 test`
but it doesn't work well.

so I am trying to fix the kernel.

When is the deadline?

**Comment by hseok-oh** [comment]
@hasw7569 

>When is the deadline?

There is no strict deadline because our plan about quantization is supporting 35 operations, and we already supporting 37 operations now. 

But recommanded deadline is until release 1.8.0 Release 1.8.0 will branch out tomorrow (8/11). So if your implementation is not merged until 8/11, supporting `log_softmax` qunatization will be delayed to next release.
