### ISSUE TITLE
How to convert nnpkgtc to nnfw_api_gtest?

### ISSUE THREAD

**Issue by glistening** [Samsung/ONE#3707]
I've been asked to put `nnfw_api_test` for my new op — https://github.com/Samsung/ONE/pull/3688#pullrequestreview-462447737

Since I have already nnpkgtc (= nnpackage + input, expected values), I thought it would be an easy job.
However, I've found that `nnfw_api_gtest` requires to write input and expected values in c++ source code.
Is there a way to convert h5 into c++ source format? How does the users usually write nnapi_tests?
If we have tfltie model, it is very easy to create nnpkgtcs by using `tflite2nnpkgtcs your.tflite`. It's all.
In addition, why do we need to use `nnfw_api_gtest` framework for model tests? why not just using `nnpkgtc`?

cc @wateret, @hseok-oh

**Comment by hseok-oh** [comment]
`nnfw_api_test` is for nnfw API validation test, not for operation test. So `nnfw_api_test` don't assume that nnpackage have golden value.

**Comment by wateret** [comment]
Sorry for the confusion. Adding a testcase to `nnfw_api_test` is not exactly what I meant. What I want is just to make the new code tested on CI. And it is just one of the many ways to ensure that.

If the test cases from https://github.com/Samsung/ONE/pull/3688#issuecomment-669715889 are tested on CI, then please ignore my comment.

**Comment by glistening** [comment]
@hseok-oh, @wateret Thank you for answer. Then, it is only required to put nnpkgtcs in CI. 

Could you please let me know where should I put nnpkgtcs (with golden data) to run nnpkgtc in CI?
As I know, there was no way at least a few months ago.

**Comment by wateret** [comment]
@mhs4670go @llFreetimell Could you please let us know about adding nnpkg test cases?

**Comment by mhs4670go** [comment]
AFAIK, we've been testing nnpkg with `push-nnpackage-test` in CI. [This](https://github.com/Samsung/ONE/issues/2113#issuecomment-647342061) helps you to know how to test nnpkg in it. 

But, it is starting from the place where `nncc` uses for resources repository. So, to count your test cases in `push-nnpakcage-test`, you have to add those cases to `nncc`'s resources repo with `recipe` which is `nncc`-defined format for creating `tflite` file using `tfl-chef`. If these bothers you because of unfamiliarity, you could add a new nnpkg test that starts from `nnfw`'s resources repo.

These are just brief explanation of what you have to need for test. Please let me know if you need more detailed explanation.

**Comment by glistening** [comment]
@mhs4670go Thank you. But I don't want `nncc` dependent solution.

**Comment by glistening** [comment]
I will close this issue since it is not necessary to add `nnfw_api_gtest` for new op tests.
