### ISSUE TITLE
[onert] Implement UNIDIRECTIONAL_SEQUENCE_LSTM on onert

### ISSUE THREAD

**Issue by hseok-oh** [Samsung/ONE#3851]
Let's implement UNIDIRECTIONAL_SEQUENCE_LSTM operation on onert

**Comment by ragmani** [comment]
Is it from the backend fee?

**Comment by hseok-oh** [comment]
>Is it from any backend free?

CPU first.

**Comment by ragmani** [comment]
Okay, I will do this.

**Comment by ragmani** [comment]
This operation is the similar `LSTM` operation. `LSTM` performs a single time step, but `UNIDIRECTIONAL_SEQUENCE_LSTM` performs all time step in lstm. So these two operations has difference as follows:
- `LSTM` operation performs a single time step in lstm with an 2-D input. But `UNIDIRECTIONAL_SEQUENCE_LSTM` performs all time steps with dynamic input unrolled the along the time dimension. And the input is either time-major or batch-major.
- `LSTM` operation generates outputs with cell state. But `UNIDIRECTIONAL_SEQUENCE_LSTM` doesn't generate cell state because it is not necessary after performing lstm.

| | LSTM | UNIDIRECTIONAL_SEQUENCE_LSTM |
|--|:--:|:--:|
| Time steps | single step | all steps |
| Inputs | 2-D | 3-D with a dimension for max time steps |
| Outputs | with cell state | without cell state |

**Comment by ragmani** [comment]
Now, onert does not support optional inputs of LSTM. So I will work on that in this task.

**Comment by ragmani** [comment]
A tflite model with `UNIDIRECTIONAL_SEQUENCE_LSTM` for MNIST : [unidirectional_sequence_lstm.zip](https://github.com/Samsung/ONE/files/5347307/unidirectional_sequence_lstm.zip)

**Comment by ragmani** [comment]
`UNIDIRECTIONAL_SEQUENCE_LSTM` have state inputs that can be constant, but haven't data.

**Comment by ragmani** [comment]
Running above tflite model works well with #4519 .
```bash
$ BACKENDS="cpu" ./Product/armv7l-linux.debug/out/bin/nnpackage_run --nnpackage usl/unidirectional_sequence_lstm -w 1 -r 1 -d output.h5 -l usl/unidirectional_sequence_lstm/metadata/tc/input.h5
Package Filename usl/unidirectional_sequence_lstm
===================================
MODEL_LOAD   takes 17.498 ms
PREPARE      takes 86.187 ms
EXECUTE      takes 2.563 ms
- MEAN     :  2.563 ms
- MAX      :  2.563 ms
- MIN      :  2.563 ms
- GEOMEAN  :  2.563 ms
===================================

$ h5diff -v --use-system-epsilon usl/unidirectional_sequence_lstm/metadata/tc/expected.h5 output.h5 

file1     file2
---------------------------------------
    x      x    /              
    x           /name          
    x      x    /value         
    x      x    /value/0       

group  : </> and </>
0 differences found
group  : </value> and </value>
0 differences found
dataset: </value/0> and </value/0>
0 differences found
```

**Comment by ragmani** [comment]
I have been done this task except to support acl backends due to a bug of LSTM layer. You can see more detail information at #4555. Now I cannot make acl backends supports this operation, and I have been done this task except it. So I close this issue.
