### ISSUE TITLE
[luci] Graph is CHANNEL_LAST after convert_nchw_to_nhwc

### ISSUE THREAD

**Issue by seanshpark** [Samsung/ONE#5686]
After applying `convert_nchw_to_nhwc` option to _circle2circle_,
circle file data format is `DataFormat_CHANNELS_LAST` which should be `DataFormat_CHANNELS_FIRST`

Code in `compiler/luci/export/src/CircleExporterImpl.cpp`
```cxx
    // TODO set this value properly
    gd._data_format = circle::DataFormat::DataFormat_CHANNELS_LAST;
```
which we need to fix.

**Comment by seanshpark** [comment]
CC @jinevening

**Comment by jinevening** [comment]
After applying `convert_nchw_to_nhwc`, data format should be `CHANNELS_LAST`. It happens to be correct as our default data format is `CHANNELS_LAST`.

The current circle schema cannot correctly represent the data format of a model produced by `onnx-tf`, because the model has both nchw operators and nhwc operators in one subgraph (see https://github.com/Samsung/ONE/issues/5487#issuecomment-753730296). To utilize the data format field in the circle schema, we need to change the schema to save `data_format` for each operator. Until then, IMHO we cannot use `data_format` field in `convert_nchw_to_nhwc`.

**Comment by seanshpark** [comment]
What was I thinking of... I think my mind went to Mars... -_-;
