### ISSUE TITLE
[one-cmds] one-build failed with error message

### ISSUE THREAD

**Issue by YongseopKim** [Samsung/ONE#6372]
After running `one-prepare-venv`, I did `one-build`. (Actually I run other cfg file for internal.)

```
dragon@loki:~/Works/github/ONE/compiler/one-cmds$ bash one-build -C ./one-build.template.cfg
/home/dragon/Works/github/ONE/compiler/one-cmds/venv/bin/python: can't open file '/home/dragon/Works/github/ONE/compiler/one-cmds/tf2tfliteV2.py': [Errno 2] No such file or directory
```

```
dragon@loki:~/Works/github/ONE/compiler/one-cmds$ find . -name "tf2tfliteV2.py"
dragon@loki:~/Works/github/ONE/compiler/one-cmds$ 
```

What should do I solve this problem?

**Comment by seanshpark** [comment]
There is a `setup` step that is not documented: actually done in release step and by SDK package step by SDK guys...

To make a release binary, run something like this in bash
```
NNAS_BUILD_PREFIX=build/release \
NNCC_WORKSPACE=build/release \
BUILD_TYPE=Release \
./nnas create-package --preset 20200630 --prefix build/install
```
It'll build from scratch and may take some time... please grab a cup of coffee...

Intermediate files will reside in `build/release` folder and release files will reside in `build/install` folder.
Binary files will reside in `build/install/bin`.
- Please add `$HOME/(ONE_PATH)/build/install/bin` to `PATH` so that executables can run in any place.
- Please read document `build/install/doc/how-to-prepare-virtualenv.txt` and follow the steps
- Please read document `build/install/doc/how-to-use-one-commands.txt`.

If there is any problem, please add more questions... (above steps may not work for some cases...)

**Comment by mhs4670go** [comment]
If above step bothers you, just download the release binary:)

**Comment by YongseopKim** [comment]
Thanks @seanshpark @mhs4670go ! I solved with the release binary. :-) I close this.
