### ISSUE TITLE
[Circle-OpSelector] Is there any way to get various tflite files?

### ISSUE THREAD

**Issue by parkeunsang** [Samsung/ONE#7671]
To test **Circle-OpSelector**, various type of tflite models must be needed.
I found some tflite files on `/build/compiler/circle-part-value-test/` folder(compiler build required). There were more than 20 files. 
And in #7661, I used `Part_Sqrt_Rsqrt_002.tflite` and `Part_Sqrt_Rsqrt_Add_002.tflite` for defining test cases.
But in that folder, some of the files were not suitable for testing because the number of operators(nodes) was too small.
So I wonder that tflite files on the folder are sufficient for testing or other tflite files could be required.
If the latter is the case, is there any way to get various tflite files which have sufficient operators?

**Comment by glistening** [comment]
I guess

1. you can put your tflite's recipe under `res/TensorFlowLiteRecipes`:
2. Then, you can convert tflite recipe to tflite, and then use your tflite. 

- I've heard all test must be in tflite recipe:  https://github.com/Samsung/ONE/issues/7606#issuecomment-913459430.
- You can find several examples by searching `TensorFlowLiteRecipies` in this repo sources.

But I am not familiar with the compiler part's test convention. Could anyone please confirm my guess is right?

@mhs4670go or @llFreetimell, or @seanshpark or @jinevening ... ( I don't know whom should I ask... )

**Comment by mhs4670go** [comment]
There are several ways to get TFLite models.

1. Download TF file from the [Tensorflow Hub](https://tfhub.dev/) and convert it to TFLite.
2. Write a recipe and convert it to TFLIte. ONE compiler manages all the recipe in `res/TensorFlowLiteRecipes` and `res/CircleRecipes`.
3. Write a python script that makes a tensorflow model. There is a tool that can help you to do this. Please see `res/TensorFlowPythonModels` and `res/TensorFlowPythonExamples`.

Anyway, 1 and 3 is for local test. You have to choose only 2 option to integrate the test you are gonna make with existing compiler project. Because real models has very big memory and may be changed depending on the schema version or something, which is why `tflchef` was introduced([README](https://github.com/Samsung/ONE/blob/2851d75a476fc695d88fbdd71e56be9548c0ff39/compiler/tflchef/README.md)). `recipe` is just a `flatbuffers` file that can be converted(cooked) into TFLite by `tflchef` with reference to TFLite schema.

All the recipe files are cooked in `common-artifacts`. You can see all the related artifacts in `build/compiler/common-artifacts/`. All the compiler modules that want to get these artifacts when they test their things just add
```cmake
get_target_property(ARTIFACTS_BIN_PATH testDataGenerator BINARY_DIR)
```
 command in their `CMkaeLists.txt`.

So, seems to me like,, you will go throw the process below.

1. Write recipes that have enough operators to test `op_selector`. For example, you will need 2 recipes per test - models before and after "selection", respectively. If it is difficult to write a recipe from scratch, you can easily make a recipe by getting a model and using a `build/compiler/tflchef/tools/reverse/tflchef-reverse` .
2. Place them at `res/TensorFlowLiteRecipes`. Then, `common-artifacts` will automatically create TFLite files when the compiler modules are built.
3. Write a test module. I think it would be good to create a test-only module separate from the `op_selector` module like `luci-value-test` or `circle-part-value-test`, etc. As I said before, referring to `luci-value-test` will be quite convenient for you to implement what you want to do:)

**Comment by glistening** [comment]
I have exactly same opinion with @mhs4670go. It is natural because I've got guide from him. : )
I think you can follow the steps above @mhs4670go explained kindly in detail. If you need more detail, you can refer other modules which uses `TensorFlowLiteRecipes`.

**Comment by parkeunsang** [comment]
@mhs4670go , @glistening  I really appreciate your comments.

**Comment by parkeunsang** [comment]
@mhs4670go I read [luci-value-test](https://github.com/Samsung/ONE/tree/master/compiler/luci-value-test)'s codes but I can't understand the flow of test.
I think `test.lst` file contains tflite recipes and `evalverify.sh` and `luci_eval_verifier.py` files are used for test.
And [CmakeLists.txt](https://github.com/Samsung/ONE/blob/master/compiler/luci-value-test/CMakeLists.txt) contains these files. But in `CmakeLists.txt`, 
Q1. I can't find **generating tflite files process using recipe**
Q2. And evalverify.sh **requires multiple options** but not in `CMakeLists.text`(only "${CMAKE_CURRENT_SOURCE_DIR}/evalverify.sh")
I think Q1 is related to 
```
add_custom_target(luci_eval_testfiles ALL DEPENDS ${TESTFILES})
```
and Q2 related to 
```
get_target_property(ARTIFACTS_BIN_PATH testDataGenerator BINARY_DIR)
```
But it's hard to understand the exact process.

**Comment by mhs4670go** [comment]
@parkeunsang 
>  I can't find generating tflite files process using recipe

> All the recipe files are cooked in `common-artifacts`.

It means all the recipes are converted into TFLite in `common-artifacts`. So agian, all the compiler modules that want to get these artifacts(including TFLite files) when they test their things just add
```cmake
get_target_property(ARTIFACTS_BIN_PATH testDataGenerator BINARY_DIR)
```
 command in their `CMakeLists.txt`.

---

> And evalverify.sh requires multiple options but not in CMakeLists.text(only

```cmake
add_test(NAME luci_value_test
  COMMAND "${CMAKE_CURRENT_SOURCE_DIR}/evalverify.sh"
          "${CMAKE_CURRENT_BINARY_DIR}"
          "${ARTIFACTS_BIN_PATH}"
          "${NNCC_OVERLAY_DIR}/venv_2_6_0"
          "$<TARGET_FILE:luci_eval_driver>"
          ${LUCI_VALUE_TESTS}
)
```

This command means
```bash
$ ${CMAKE_CURRENT_SOURCE_DIR}/evalverify.sh ${CMAKE_CURRENT_BINARY_DIR} ${ARTIFACTS_BIN_PATH} ${NNCC_OVERLAY_DIR}/venv_2_6_0 $<TARGET_FILE:luci_eval_driver> ${LUCI_VALUE_TESTS}
```

`${CMAKE_CURRENT_BINARY_DIR} ${ARTIFACTS_BIN_PATH} ${NNCC_OVERLAY_DIR}/venv_2_6_0 $<TARGET_FILE:luci_eval_driver> ${LUCI_VALUE_TESTS}` are arguments of `evalverify.sh`.

**Comment by glistening** [comment]
> Q1. I can't find **generating tflite files process using recipe**

If you're looking for where tflite generation is done, please see `compiler/common-artifacts/CMakeLists.txt`. `common-artifacts` is included by `requires.cmake`, which has `require("common-artifacts")`.
