### ISSUE TITLE
Enable SVDF Op

### ISSUE THREAD

**Issue by BalyshevArtem** [Samsung/ONE#8203]
## What?
Let's support svdf operation.
## Why?
One of the benchmarks for tflite micro is the following model: 

[model.zip](https://github.com/Samsung/ONE/files/7762412/model.zip)

![keyword_model](https://user-images.githubusercontent.com/43214667/147089001-6e5dc3d7-c091-44e1-89fe-971f25a4f58b.png)

At this moment we cannot run this model on the `luci-interpreter`. One of the problems is the presence of an SVDF operation that needs to be supported. 
To understand better you can see this issue #7598 and this comment https://github.com/Samsung/ONE/issues/7598#issuecomment-916384853

## How?
First of all we need support this parts:
- [x] tflite2circle #8204
- [x] common-artifacts add item to exclude new recipes #8282
- [x] res/TensorFlowLiteRecipes #8285
- [x] tflchef #8284
- [x] tfldump and circledump #8286 #8287
- [x] luci/lang  #8291
- [x] luci/import #8292 
- [x] luci/service
- [ ] luci/pass
- [x] luci/log, luci/logex
- [x] luci/tests addread
- [x] luci/exports
- [x] luci/tests addwrite
- [x] luci-interpreter
- [x] luci-interpreter/pal
- [x] luci/partition
- [ ] common-artifacts remove items added

**Comment by BalyshevArtem** [comment]
+cc @binarman

**Comment by seanshpark** [comment]
Please prepare a full working draft PR for this new Op to verify it's working
- perpare tflchef recipe(s) for "testing" in `TensorFlowLiteRecipes` like other Ops.
- revise `compiler/tflchef` to produce tflite file from recipe file.

`compiler/common-artifacts` will fail if any module may fail, when you add the recipe file(s)

**Comment by llFreetimell** [comment]
@BalyshevArtem 

I am refactoring `luci/export` with #8198.
It may affect your (draft)code for `luci/export`.
I will keep an eye on this issue and let you know if there are something to be updated :)
Meanwhile, I will finish #8198 ASAP!

**Comment by binarman** [comment]
It is hard to manipulate model from top comment, because it does not contain tensor names and model description string.
This is fixed version of this model: [kws.zip](https://github.com/Samsung/ONE/files/7774989/kws.zip) (kws stands for KeyWord Spotting, it is model from google to recognize "ok, google" phrase)

<details>

<summary>related files</summary>

cut version: [kws_cut.zip](https://github.com/Samsung/ONE/files/7774992/kws_cut.zip)
select_operator.py hack patch to fix the model: [select_operator.patch.txt](https://github.com/Samsung/ONE/files/7774997/select_operator.patch.txt)

</details>

**Comment by llFreetimell** [comment]
As #8198 is finished, please rebase with latest commit :D

**Comment by seanshpark** [comment]
I've reviewed some codes in tflite and found that
- `variable` is attribute of the Tensor, but CircleNode does not have Tensor
- `state` input tensor is a `variable` tensor
- to represent input tensor for `variable` we need to introduce new CircleNode
  - this may cause lots of code changes that exist around
  - as a workaround we can reuse `CircleOutputDummy` that has similar characteristic having no input
- we need to do both import and export for this tensor with `viariable`
  - if not, circle2circle will not produce a tensor with variable in circle file
- tfldump and circledump needs to reflect this tensor with `variable

from tflite kernel implementation (this maybe incorrect)
- `scratch` tensor are additionally created in kernel init stage to persist `state` tensor
- each `scratch` tensor index is written to `node->temporaries` buffer
- `scratch` tensor contents are copied `state` tensor before running the kernel
- kernel uses `scratch` tensor as to produce the output (in `ApplyTimeWeightsBiasAndActivation`)

**Comment by seanshpark** [comment]
What I want to do for this task are;
- revise tfldump and circledump to reflect tensor with `variable`
- make a draft PR based on #8231 but what I think is better for _luci_
- I will not post a PR of #8231 but for new ones, with agreement from @BalyshevArtem

> as a workaround we can reuse `CircleOutputDummy`

I suggested to work with `CircleOutputDummy` as this node is considered (but not fuilly) on other modules with hope there will be no critical problems.
I'll work on `CircleVariable` or whatever name, new virtual node.
When this node lands and become stable, we can revise _luci-interpreter_ to change to use this node.

@BalyshevArtem @binarman , please share your thoughts.

**Comment by BalyshevArtem** [comment]
I agree with your plan 👍
 
> I'll work on `CircleVariable` or whatever name, new virtual node. 

I think new virtual node where we can use new attribute `variable` is better than using the `CircleOutputDummy`.

Actually, there is one more moment
As @binarman  found out that this `state input tensor` isn't  persistent between inferences: if we run the model several times, then each time something is added to the scratch tensor and the main result of the work of the SVDF op changes. That is why new virtual node can be good idea for such tensor, due to we should save tensor data after inference, but don't export it as `state input tensor` is variable tensor and its buffer is empty.

Also I found in tflite interpreter variable tensors with not empty buffer is not supported now. 
```c++
    bool is_variable = tensor->is_variable();
    if (buffer_ptr) {
      if (is_variable) {
        error_reporter_->Report(
            "Tensor %d is a variable tensor with buffer. "
            "It's not supported now.\n",
            i);
        status = kTfLiteError;
      }
```

**Comment by seanshpark** [comment]
I've posted #8279 (started from #8231) as to validate my thougths and to discover for other modules as I wrote.
Next step for me; I'll wait for your code to land; at the same time I'll post what I've changed that can be posted. 
Please review my changes and share what you think; and we need to discuss and settle down the conflicts.

**Comment by BalyshevArtem** [comment]
> I've posted #8279 (started from #8231) as to validate my thougths and to discover for other modules as I wrote. Next step for me; I'll wait for your code to land; at the same time I'll post what I've changed that can be posted. Please review my changes and share what you think; and we need to discuss and settle down the conflicts.

I think all the changes look fine! Thank you for your draft!

**Comment by BalyshevArtem** [comment]
according to https://github.com/Samsung/ONE/pull/8231#issuecomment-1014067718, I changed the plan for adding changes (see above).

**Comment by seanshpark** [comment]
@BalyshevArtem , current master + draft 8279 seems to fail SVDF_001 recipe.

> [ 71%] Generate input.h5 and expected.h5 in SVDF_001.opt/metadata/tc
testDataGenerator: .../compiler/luci-interpreter/include/luci_interpreter/core/Tensor.h:43: int32_t luci_interpreter::Shape::dim(int) const: Assertion `i >= 0 && i < static_cast<int>(_dims.size())' failed.
Aborted (core dumped)

this happens when build. I'm not sure what went wrong. Could you please check if you also have this problem? or it maybe be only my problem.

**Comment by seanshpark** [comment]
> current master + draft 8279 seems to fail SVDF_001 recipe.

Found it: in _luci-interpreter_ kernel, bias() is optional but initial draft draft doesn't handle this.

**Comment by m-bronnikov** [comment]
> @BalyshevArtem , current master + draft 8279 seems to fail SVDF_001 recipe.
> 
> > [ 71%] Generate input.h5 and expected.h5 in SVDF_001.opt/metadata/tc
> > testDataGenerator: .../compiler/luci-interpreter/include/luci_interpreter/core/Tensor.h:43: int32_t luci_interpreter::Shape::dim(int) const: Assertion `i >= 0 && i < static_cast(_dims.size())' failed.
> > Aborted (core dumped)
> 
> this happens when build. I'm not sure what went wrong. Could you please check if you also have this problem? or it maybe be only my problem.

The reason of trouble: SVDF operator expects 5 positional inputs, but when 4 are given (exclude bias) operator initializes `bias` with `input_actication_state` deta.

Let me explain with example using netron. 

Model with bias (SVDF_000):

![image](https://user-images.githubusercontent.com/43731397/151634535-3224629d-690f-4466-8a5b-f785283d7ca7.png)


**state** has shape `[1, 512]` and dtype `int16_t`. But model without provided bias (SVDF_001) uses this description for bias (which must not exist).

![image](https://user-images.githubusercontent.com/43731397/151634754-23f074a3-d506-4555-9883-63391e68c763.png)

I think this baggy behavior happens due to in SVDF_001 only 4 inputs for SVDF operator provided:

https://github.com/Samsung/ONE/blob/7cfd6cd4c132efcf432d45e4e6275889229eeae1/res/TensorFlowLiteRecipes/SVDF_001/test.recipe#L44-L47

But SVDF operator expects 5 inputs with 1 optional bias:

```diff
diff --git a/res/TensorFlowLiteRecipes/SVDF_001/test.recipe b/res/TensorFlowLiteRecipes/SVDF_001/test.recipe
index bddb2bca7..e622cec68 100644
--- a/res/TensorFlowLiteRecipes/SVDF_001/test.recipe
+++ b/res/TensorFlowLiteRecipes/SVDF_001/test.recipe
@@ -44,6 +44,7 @@ operation {
   input: "ifm"
   input: "weight_feature"
   input: "weight_time"
+  input" ""
   input: "input_activation_state"
   output: "ofm"
 }
```

**Comment by seanshpark** [comment]
Can we close this issue?

**Comment by BalyshevArtem** [comment]
Looks like issue is resolved. Let's close!
