### ISSUE TITLE
[one-cmds] import onnx_legalizer difference

### ISSUE THREAD

**Issue by seanshpark** [Samsung/ONE#8213]
Current local setup has `onnx_legalizer.py` which will enable `import onnx_legalizer`,
where package setup version doesn't as currently this file isn't included.

From this difference I had a problem of difference, where local setup compiled without problem,
but my test machine installed with debian package failed.

**Comment by seanshpark** [comment]
What I think as for now
(1) use environment variable to enable import onnx_legalizer (for temporary)
(2) add `one-import-onnx` option to enable execute `onnx_legalizer.legalize(onnx_model)`

Another thought;
For `onnx_legalizer.legalize()`, this method is doing RNN/LSTM unrolling as I understand.
If this method is for unrolling, how about chaning method name to `unroll_rnn` ?
If not, I think we need to split actions and call by option from `one-import-onnx`

cc @binarman

**Comment by seanshpark** [comment]
Posted #8215

**Comment by binarman** [comment]
@seanshpark 
> If this method is for unrolling, how about changing method name to unroll_rnn ?

I imagined this method as a top level interface to "legalize" onnx model so it could be processed by later stages, like `onnx->tflite`, `tflite2circle` and `circle2circle` without errors.

For now it only capable of transforming `RNN` and `LSTM` layers, because this is the only problems I faced so far. :slightly_smiling_face: 

I implemented unrolling, instead of general while loop, because it is relative simple and reliable method:
- debugging code inside while loop could be painful
- I did not see NN models where it is needed

**Comment by binarman** [comment]
To make it clear.
Main purpose of `onnx_legalizer` is to **fix problematic ONNX models** that we can not convert for some reason:
- errors in third party converters
- unsupported complex operations
- etc.

If these problems are resolved (for example by updating some converters/frameworks) we can simply remove/disable code in `onnx_legalize.py`

**Comment by seanshpark** [comment]
I think issue from not much understanding is resolved and adding option is in progress.
