### ISSUE TITLE
[one-quantize] Improve MPQ interface

### ISSUE THREAD

**Issue by jinevening** [Samsung/ONE#9170]
## What

Let's improve interface of quantization configuration file (qconf) to help users easily select target layers.

## Why

Currently, users should write the name/dtype/granularity of each layer in the qconf file.

```json
{
    "default_quantization_dtype" : "int16",
    "default_granularity" : "channel",
    "layers" : [
        {
            "name" : "MobilenetV1/Logits/Conv2d_1c_1x1/BiasAdd",
            "dtype" : "uint8",
            "granularity" : "channel"
        },
        {
            "name" : "MobilenetV1/Logits/SpatialSqueeze",
            "dtype" : "uint8",
            "granularity" : "channel"
        },
        {
            "name" : "MobilenetV1/Predictions/Reshape_1",
            "dtype" : "uint8",
            "granularity" : "channel"
        }
    ]
}
```

We can avoid duplication by supporting multiple names for the same dtype/granularity.

```json
{
    "default_quantization_dtype" : "int16",
    "default_granularity" : "channel",
    "layers" : [
        {
            "name" : ["MobilenetV1/Logits/Conv2d_1c_1x1/BiasAdd",
                      "MobilenetV1/Logits/SpatialSqueeze",
                      "MobilenetV1/Predictions/Reshape_1"]
            "dtype" : "uint8",
            "granularity" : "channel"
        }
    ]
}
```

Further improvement would be the use of layer number, which will be useful for layers with very long names.

```json
{
    "default_quantization_dtype" : "int16",
    "default_granularity" : "channel",
    "layers" : [
        {
            "number" : [28, 29, 30]
            "dtype" : "uint8",
            "granularity" : "channel"
        }
    ]
}
```

Goal 1: Support array of names
Goal 2: Support use of layer number

CC @Samsung/one_quantizer

**Comment by glistening** [comment]
@jinevening I like your suggestion though I am not the member of one_quantizer. : )

### 1. consistent name for layer number 

@hseok-oh, @chunseoklee and I are also working for nnpkg spec and related tools to support multiple models.
I also would like to identify layer by number, rather than long names. But I thought the term `location`, which is the name `netron` uses. But I find several names for same concept.

I think it comes from index of operators in SubGraph.

```sql
// The root type, defining a subgraph, which typically represents an entire
// model.
table SubGraph {
  ...
  // All operators, in execution order.
  operators:[Operator];
}
```

`tflitefile_tool` does not give name https://github.com/Samsung/ONE/tree/master/tools/tflitefile_tool#example-1. But it uses the layer index list as opcodelist.

Perhaps candidates are `number`, `location`, `index`, ...

Personally I prefer `layer index` or `op index`.

### 2.  names and numbers

If "number" is going to have multiple items, what about using `names` and `numbers`?

**Comment by jinevening** [comment]
@glistening  Thanks for the comment. Among the candidates, I prefer `index` too :)

For multiple items, `names` and `indices` would be good.

**Comment by jinevening** [comment]
Done.
