### ISSUE TITLE
[one-cmds] Share optimization configure file as docker volume

### ISSUE THREAD

**Issue by holawan** [Samsung/ONE#9715]
Regarding `onecc` dockerizing, I'm considered about how to include the `-O` function.

As far as I know, in the ONE project, the optimization option is written in the configure file one by one and `onecc` is executed. Because of this inconvenience, the `-O` option is configured to suit the purpose, and then the `-O` option is applied to suit the intention.

When referring to the `_get_optimization_list` function in [utils.py](https://github.com/Samsung/ONE/blob/master/compiler/one-cmds/utils.py) , it is understood that the option should be placed in the folder after creating the "optimization" folder in the location below.

```
#utils.py 
    [one hierarchy]
    one
    ├── backends
    ├── bin
    ├── doc
    ├── include
    ├── lib
    ├── optimization
    └── test
```
When the Debian package is installed, we can use `onecc`. However, to use the `-O` option, I need to create an "optimization" folder in the "/usr/share/one" location and create a file in the `O*.cfg` format in this location. I'm thinking about how to share this as a volume in the Dockerizing process.

I'd appreciate it if you could leave a good opinion.

related issue : #9712 

/cc [@Samsung/ootpg](https://github.com/orgs/Samsung/teams/ootpg)

**Comment by seanshpark** [comment]
I think you should not use `-O` as this is under development

CC @mhs4670go

**Comment by mhs4670go** [comment]
As @seanshpark said, you don't have to consider this issue as of now.

FYI for future,

There are a few options for this.

### 1. Mount `optimization` directory

I don't know where `one-docker` driver will be placed but I think it will be `/usr/share/one/bin/`. So, we can just mount `optimization` directory.

### 2. Do nothing

`optimization` folder is still experimental feature. I think the files inside the `optimization` directory will be provided by ONE developer rather than the users, which means the files are included in future ONE release, which means the files are automatically installed.

### 3. Get optimization list from working(or current) directory

Number 2 option doesn't allow the users to create their own optimization option. It would be enough but if someone thinks it isn't, this number 3 option will do the trick.

---

 Also, FYI, the `one-codegen` has the same issue because of `backends` directory. But, we can take a rain check on this as well:)

**Comment by seanshpark** [comment]
> ... but I think it will be /usr/share/one/bin/. ...

this is interesting question... @jyoungyun , where do you expect to be installed?

**Comment by jyoungyun** [comment]
> I don't know where `one-docker` driver will be placed but I think it will be `/usr/share/one/bin/`. So, we can just mount `optimization` directory.

I think it is enough to mount `HOME` and `/tmp` directory. We don't need to mount `/usr/share/one/bin` directory because the docker container already have inside docker container. In my opinion, it would be better not to specify the location where the file is loaded in `-O` option.

Anyway, I think this option is out of scope in this ootpg project as of now. How about proceeding without considering `optimization` option?

**Comment by holawan** [comment]
> Anyway, I think this option is out of scope in this ootpg project. How about proceeding without considering `optimization` option?

Thank you for your opinion.

We will proceed without considering the contents mentioned in the issue. 

Is there anything else to say on this issue?

**Comment by jyoungyun** [comment]
The optimization directory issue is not related to our project. So there seems to be nothing more to talk about on this issue. 
Thank you for finding out what I missed. :)

**Comment by holawan** [comment]
Thank you for everyone for the comments:)
