### ISSUE TITLE
[ONE-Dockerizing] debian package related to onecc-docker

### ISSUE THREAD

**Issue by Seunghui98** [Samsung/ONE#9750]
## What
We created a onecc-docker debian package.

## Why
We have to make it a Debian package to run the onecc-docker.

## How
1. Structure
```
$ tree
.
├── DEBIAN
│   ├── control
│   ├── install
│   └── preinst
└── usr
    ├── bin
    │   └── onecc-docker
    └── share
        └── one
            └── docker
                ├── Dockerfile
                └── copyright
```
- `usr/bin/onecc-docker`, `usr/share/one/docker/Dockerfile`
  - Related issues : [#9738](https://github.com/Samsung/ONE/issues/9738)
  - Parent issues : [#9712](https://github.com/Samsung/ONE/issues/9712)
  - Related PR : [#9737](https://github.com/Samsung/ONE/pull/9737)
- The Dockerfile path has been set so that onecc-docker file can use Dockerfile in `usr/share/one/docker`

2. Test
1) Create onecc-docker debian package
```
$ sudo dpkg -b onecc-docker_1.21.0_amd64
```

2) Install the onecc-docker debian package
```
$ sudo apt-get install -y ./onecc-docker_1.21.0_amd64.deb
```

3) The result of executing a simple onecc command to see if onecc-docker works well
```
$ onecc-docker --version
build Docker image ...
Dockerfile successfully built.
onecc version 1.21.0
Copyright (c) 2020-2022 Samsung Electronics Co., Ltd. All Rights Reserved
Licensed under the Apache License, Version 2.0
https://github.com/Samsung/ONE
```

/cc @Samsung/ootpg_docker

**Comment by seanshpark** [comment]
the main comment has similar contents with the link and the parent links.
Q) why add a new issue? I mean why do you put so much efforts to write this issue?

**Comment by Seunghui98** [comment]
@seanshpark 
I uploaded an issue to include the related content of draft code of onecc-docker debian package. Would selling similar issues on one topic cause confusion for others?

**Comment by seanshpark** [comment]
> Would selling similar issues on one topic cause confusion for others?

I think think it's about the confusion with multiple issues posted.
But as I wrote, IMHO, (1) it seems you are putting much effort for writing this issue. Is it really necessary? 
(2) there are lots of subjects in the main comment. what is the main point of this issue?
(3) I think for explaining the background and benefits and the task just one issue is OK. but I don't think posting all issues like this is good.

**Comment by jyoungyun** [comment]
@Seunghui98

>   - Related issues : [#9738](https://github.com/Samsung/ONE/issues/9738)

I think this issue is not related to #9738 issue because this issue contains version issue.
Instead, the parent issue of this issue should be #9712. :)


@seanshpark 

> (1) it seems you are putting much effort for writing this issue. Is it really necessary?
> (2) there are lots of subjects in the main comment. what is the main point of this issue?
> (3) I think for explaining the background and benefits and the task just one issue is OK. but I don't think posting all issues like this is good.

I asked her to create a new issue for debian packaing.. Because I think we didn't discuss debian packaging in any issue except #9712 main project issue. But, #9712 is a main project issue so I thought that this issue is not an appropriate location to discuss debian packaging, so I suggested to create a new issue.

However, I agree with your opinion that one issue for background, advantage, and task is enough.
Since other issues are almost done, the issue will be closed when the related PR is merged.

I will help SSAFY team to sort out the issue and manage it so that unnecessary issues are not created. :)

**Comment by Seunghui98** [comment]
@jyoungyun 

Thank you for the comment on the issue. I changed the contents of the related issue as you advised. :)
