### ISSUE TITLE
[tools] Support connection info packaging on model2nnpkg

### ISSUE THREAD

**Issue by hseok-oh** [Samsung/ONE#9802]
Previous issue: #9116

Let's support packaging with connection info on `model2nnpkg.sh`. (`tools/nnpackage_tool/model2nnpkg/model2nnpkg.sh`)

**Comment by glistening** [comment]
Let's define args to create the following connections.
```
$ cat nnpackage/examples/v1.3.0/two_tflites/metadata/MANIFEST 
{
  "major-version" : "1",
  "minor-version" : "3",
  "patch-version" : "0",
  "configs"       : [  ],
  "models"        : [ "mv1.0.tflite", "mv1.1.tflite" ],
  "model-types"   : [ "tflite", "tflite" ],
  "pkg-inputs"    : [ "0:0:0" ],
  "pkg-outputs"   : [ "1:0:0" ],
  "model-connect" : [ { "from" : "0:0:0", "to" : [ "1:0:0" ] } ]
}
```

**Comment by glistening** [comment]
Here are some candidates:

### Candidate 1
- Use the same name for argument name
- Use `..` to separate `from` and `to` ( I used two `.`s because one `.` looks like a number ­— e.g. `0:0:0.1:0:0` )
```
$ model2nnpkg --pkg-inputs=0:0:0 --pkg-outputs=1:0:0 --model-connet=0:0:0..1:0:0
```
- For multiple items, use `,` as separator
```
$ model2nnpkg --pkg-inputs=0:0:0,1:0:0 --pkg-outputs=2:0:0,2:0:1 --model-connet=0:0:0..2:0:0,1:0:0..2:0:1
```
- It requires long option support. We may use external `getopt` command instead of bash `getopts`.

### Candidate 2
- Use file to get `pkg-inputs`, `pkg-outputs`, `model-connect` like `tflitefiletools/select_operator.py`
- We need to define the format in the file above, and parse it.
- It may be good for large size of input/output/connections.

**Comment by glistening** [comment]
> ### Candidate 1
> ...
>     * It requires long option support. We may use external `getopt` command instead of bash `getopts`.
 
It may be better not to use `getopt` because it requires users to install `getopt` and I am not sure `getopt` is installed by default on Ubuntu.

**Comment by hseok-oh** [comment]
Currently, coonection info is handled by python script arguemnt `--io-info`. (#10243)
